using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ReSellHub.Api.Models;

public class Category { public int Id { get; set; } [Required, StringLength(80)] public string Name { get; set; } = ""; [StringLength(80)] public string Slug { get; set; } = ""; [StringLength(10)] public string Icon { get; set; } = "📦"; public int SortOrder { get; set; } public bool IsActive { get; set; } = true; public ICollection<Product> Products { get; set; } = new List<Product>(); }
public class ProductImage { public int Id { get; set; } public int ProductId { get; set; } [Required, StringLength(500)] public string ImageUrl { get; set; } = ""; public bool IsPrimary { get; set; } public int SortOrder { get; set; } public Product Product { get; set; } = null!; }
public class AppUser { public int Id { get; set; } [Required, StringLength(100)] public string DisplayName { get; set; } = ""; [Required, StringLength(255)] public string Email { get; set; } = ""; [Required, StringLength(500)] public string PasswordHash { get; set; } = ""; [StringLength(30)] public string Phone { get; set; } = ""; [StringLength(20)] public string Role { get; set; } = "Buyer"; public bool IsActive { get; set; } = true; public DateTime CreatedAt { get; set; } = DateTime.UtcNow; public ICollection<Address> Addresses { get; set; } = new List<Address>(); public ICollection<Product> Products { get; set; } = new List<Product>(); public ICollection<ShoppingCart> Carts { get; set; } = new List<ShoppingCart>(); public ICollection<Order> Orders { get; set; } = new List<Order>(); public ICollection<Favorite> Favorites { get; set; } = new List<Favorite>(); }
public class Address { public int Id { get; set; } public int UserId { get; set; } [Required, StringLength(60)] public string RecipientName { get; set; } = ""; [Required, StringLength(30)] public string Phone { get; set; } = ""; [Required, StringLength(20)] public string PostalCode { get; set; } = ""; [Required, StringLength(40)] public string City { get; set; } = ""; [Required, StringLength(40)] public string District { get; set; } = ""; [Required, StringLength(300)] public string Street { get; set; } = ""; public bool IsDefault { get; set; } public AppUser User { get; set; } = null!; }
public class ShoppingCart { public int Id { get; set; } public int UserId { get; set; } public DateTime UpdatedAt { get; set; } = DateTime.UtcNow; public AppUser User { get; set; } = null!; public ICollection<CartItem> Items { get; set; } = new List<CartItem>(); }
public class CartItem { public int Id { get; set; } public int CartId { get; set; } public int ProductId { get; set; } [Range(1, 999)] public int Quantity { get; set; } = 1; public DateTime AddedAt { get; set; } = DateTime.UtcNow; public ShoppingCart Cart { get; set; } = null!; public Product Product { get; set; } = null!; }
public class Favorite { public int Id { get; set; } public int UserId { get; set; } public int ProductId { get; set; } public DateTime CreatedAt { get; set; } = DateTime.UtcNow; public AppUser User { get; set; } = null!; public Product Product { get; set; } = null!; }
public class Order { public int Id { get; set; } [Required, StringLength(30)] public string OrderNumber { get; set; } = ""; public int UserId { get; set; } [Required, StringLength(30)] public string Status { get; set; } = "Pending"; [Required, StringLength(30)] public string PaymentStatus { get; set; } = "Unpaid"; [Required, StringLength(30)] public string ShippingStatus { get; set; } = "Preparing"; [Column(TypeName = "decimal(18,2)")] public decimal Subtotal { get; set; } [Column(TypeName = "decimal(18,2)")] public decimal ShippingFee { get; set; } [Column(TypeName = "decimal(18,2)")] public decimal TotalAmount { get; set; } [Required, StringLength(60)] public string RecipientName { get; set; } = ""; [Required, StringLength(30)] public string RecipientPhone { get; set; } = ""; [Required, StringLength(500)] public string ShippingAddress { get; set; } = ""; public DateTime CreatedAt { get; set; } = DateTime.UtcNow; public AppUser User { get; set; } = null!; public ICollection<OrderItem> Items { get; set; } = new List<OrderItem>(); }
public class OrderItem { public int Id { get; set; } public int OrderId { get; set; } public int? ProductId { get; set; } [Required, StringLength(200)] public string ProductName { get; set; } = ""; [Column(TypeName = "decimal(18,2)")] public decimal UnitPrice { get; set; } public int Quantity { get; set; } [Column(TypeName = "decimal(18,2)")] public decimal LineTotal { get; set; } public Order Order { get; set; } = null!; public Product? Product { get; set; } }
